### ISSUE TITLE
BUG: Multiple classes with the same name generated

### ISSUE THREAD

**Issue by musukvl** [dmitry-pavlov/openapi-connected-service#23]
I have many endpoints and the plugin generates multiple classes with the same name. 
![image](https://user-images.githubusercontent.com/3954761/52090279-f1f82c80-25c1-11e9-87d2-10de66af98d7.png)

it looks like the issue is in .nswag configuration

![image](https://user-images.githubusercontent.com/3954761/52089785-7e095480-25c0-11e9-8085-867b0a329e89.png)

**Comment by dmitry-pavlov** [comment]
Thanks for contributing @musukvl ! This will be added to the next version

**Comment by dmitry-pavlov** [comment]
Fixed in [OpenAPI (Swagger) Connected Service v1.1.1](https://marketplace.visualstudio.com/items?itemName=dmitry-pavlov.OpenAPIConnectedService)
