### ISSUE TITLE
Update VS extension to support Visual Studio 2019

### ISSUE THREAD

**Issue by dmitry-pavlov** [dmitry-pavlov/openapi-connected-service#30]

**Comment by dmitry-pavlov** [comment]
Update VS extension to support Visual Studio 2019 - see https://devblogs.microsoft.com/visualstudio/how-to-upgrade-extensions-to-support-visual-studio-2019/

**Comment by dmitry-pavlov** [comment]
Added support for VS 2019 - download from VS Tools and Extensions or from VS Marketplace [page](https://marketplace.visualstudio.com/items?itemName=dmitry-pavlov.OpenAPIConnectedService).

**Comment by xperiandri** [comment]
@dmitry-pavlov you need to fix manifest
It requires Connected Services component which is not available in 2019

**Comment by dmitry-pavlov** [comment]
@xperiandri thanks for hands up! Unfortunatelly, according to Angelos Petropoulos [MSFT] 
> Microsoft Connected Services have been deprecated in VS 2019. Please use standard Visual Studio extensibility points instead: https://docs.microsoft.com/en-us/visualstudio/extensibility/

See [Microsoft/ConnectedServices issue](https://github.com/Microsoft/ConnectedServices/issues/4)

So to support VS2019 I will need to re-imlement the extension from scratch as a VS package.

**Comment by dmitry-pavlov** [comment]
Relevant bug report https://developercommunity.visualstudio.com/content/problem/468751/vs2019-preview-cannot-install-connected-service-ex.html

**Comment by dmitry-pavlov** [comment]
Connected Services will be restored in the first update to Visual Studio 2019 (version 16.1)
