### ISSUE TITLE
VS2019: The following references must be present before installation can Continue:  Microsoft Connected Services

### ISSUE THREAD

**Issue by dmitry-pavlov** [dmitry-pavlov/openapi-connected-service#31]
When you are trying to install it from VS2019 Preview I am getting a “Dependency Alert”:

```
“The following referencies must be present before installation can Continue”:

Microsoft Connected Services
```

The error dialog recommends to find this on VS marketplace, but it doesn’t exist there. So it seems there is a problem with supporting connected service extensions in VS2019 Preview.

https://developercommunity.visualstudio.com/content/problem/468751/vs2019-preview-cannot-install-connected-service-ex.html

**UPDATE**: 
Extension works fine with VS2017 at the moment. And will work fine with VS2019 as well once Visual Studio 2019 version 16.1 released.

**Comment by dmitry-pavlov** [comment]
According to Angelos Petropoulos [MSFT] · 17 hours ago 
> Microsoft Connected Services have been deprecated in VS 2019. Please use standard Visual Studio extensibility points instead: https://docs.microsoft.com/en-us/visualstudio/extensibility/

**Comment by ShamilS** [comment]
Still can't get added "OpenAPI (Swagger) Connected Service” extension to VS2019 (v.16.01, last updated 10.04.2019). Should I wait for VS2019 v.16.1 general availability?

**Comment by dmitry-pavlov** [comment]
Yes, we should wait for VS2019 v.16.1 - [this](https://developercommunity.visualstudio.com/content/problem/468751/vs2019-preview-cannot-install-connected-service-ex.html) is pending for release

**Comment by ShamilS** [comment]
OK. 
Just wanted to note it's confusing that the last record at [the web page you're referring to](https://developercommunity.visualstudio.com/content/problem/468751/vs2019-preview-cannot-install-connected-service-ex.html) states:

 _Solution Visual Studio Feedback System · Apr 03 at 03:02 AM. A fix for this issue has been released! Install the most recent release from https://visualstudio.microsoft.com/downloads/ . Thank you for providing valuable feedback which has helped improve the product._

when actual fix for this issue isn't yet available in VS2019 updates.
It might help to not confuse others if you comment there about current state/availability of this fix?

**Comment by dmitry-pavlov** [comment]
@ShamilS note the later comment "A **fix for this issue has been internally implemented and is being prepared for release.** We'll update you once it becomes available for download."

**Comment by ShamilS** [comment]
OK. I went reading straight the last record in the **Solutions** section and I missed the above comment from Angelo Petropoulos.

**Comment by dmitry-pavlov** [comment]
The bug will be **closed** once Visual Studio 2019 **version 16.1 released**.

**Comment by dmitry-pavlov** [comment]
I have tried the following [VS2019 previews](https://visualstudio.microsoft.com/vs/preview/)  - 'Microsoft Connected Services' are not restored back yet, so still doesn't work with:
- `Visual Studio Community 2019 Preview (16.1.0 Preview 1.0)`
- `Visual Studio Enterprise 2019 Preview (16.1.0 Preview 1.0)`
So keep waiting...

**Comment by dmitry-pavlov** [comment]
Update from [Angelos Petropoulos](https://developercommunity.visualstudio.com/comments/533812/view.html):
> I just pinged the engineering team that owns this feature. They are currently estimating Dev16.1 Preview 3

**Comment by JRC86** [comment]
Is there a workaround for this issue? Something we can use for now.

**Comment by dmitry-pavlov** [comment]
> Is there a workaround for this issue? Something we can use for now.
Unfortunately, no. We should wait for 16.1 Preview 3 - at the moment the latest [preview](https://visualstudio.microsoft.com/vs/preview/) version available is 16.1 Preview 2.

**Comment by dmitry-pavlov** [comment]
Visual Studio 2019 version 16.1 Preview 3 has been [released](https://devblogs.microsoft.com/visualstudio/visual-studio-2019-version-16-1-preview-3) but the #MicrosoftConnectedServices is still missed. So the [issue](https://developercommunity.visualstudio.com/content/problem/468751/vs2019-preview-cannot-install-connected-service-ex.html) is still not addressed. 😭 😭 😭  crying out loud 
![image](https://user-images.githubusercontent.com/1560778/57249822-9e78fd00-704e-11e9-9763-d0f1dd81038e.png)

**Comment by JRC86** [comment]
Guess we'll have to wait a bit further.

**Comment by JRC86** [comment]
VS 2019 16.1.0 has been released.

**Comment by zacuke** [comment]
I still can't install this extension after updating to 16.1.0

**Comment by JRC86** [comment]
@zacuke. You need to change source.extension.vsixmanifest to support Microsoft.ConnectedServices 16+

**Comment by staticdev** [comment]
Where do I change that @JRC86 ?

**Comment by dmitry-pavlov** [comment]
Now extension works fine for Visual Studio 2019. Verified in:
- Visual Studio Enterprise 2019 Preview Version 16.2.0 Preview 1.0 (now works as expected)
- Visual Studio Community 2019 Preview Version 16.2.0 Preview 1.0 (now works as expected)
- Visual Studio Community 2017 Preview Version 15.9.12 (keeps working as before)

Credits to @zacuke and the Visual Studio team. Thank you!

P.S. This issue is now fixed as well https://developercommunity.visualstudio.com/content/problem/468751/vs2019-preview-cannot-install-connected-service-ex.html

**Comment by staticdev** [comment]
@dmitry-pavlov So it doesn't work on 16.1?? I need 16.2 Preview?

**Comment by dmitry-pavlov** [comment]
@staticdev right, you need to update to 16.2. I have no luck with 16.1. make sure you also updated extension to [v1.2.2](https://github.com/dmitry-pavlov/openapi-connected-service/blob/master/docs/CHANGELOG.MD#122-2019-05-23) - it is already [published](https://marketplace.visualstudio.com/items?itemName=dmitry-pavlov.OpenAPIConnectedService) to VS Marketplace so you should see it from VS as well.

**Comment by JRC86** [comment]
@dmitry-pavlov Any specific error/issue for 16.1?

**Comment by dmitry-pavlov** [comment]
@JRC86 VS2019 v16.1 didn't show the extension within the Connected Services window when you click Add Connected Service. At least to me :) If that works on your side with VS2019 v16.1 - well, that's great! But I have got this working well only starting from VS2019 v16.2. Does it make sense?

**Comment by JRC86** [comment]
It works for me. The extension shows up for me. I'll see if i can revert anything I've done that made it work for me :)

**Comment by ShamilS** [comment]
I have just checked OpenAPI (Swagger) Connected Service extension is working now for me too in VS2019 update - Version 16.1.1 from May 23, 2019.
